name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        dotnet-version: [ "8.0.x", "7.0.x" ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{matrix.dotnet-version}}

    - name: Restore
      run: dotnet restore src/AutomationSolution.sln

    - name: Build
      run: dotnet build src/AutomationSolution.sln --no-restore -c Release

    - name: Publish API 
      run: dotnet publish src/Automation.Api -c Release -o out

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-${{matrix.dotnet-version}}
        path: out

    - name: Test
      run: dotnet test src/AutomationSolution.sln/ --no-build -c Release